/*
 * The canonical order spec: the single artifact from which a production
 * file is regenerated byte-identically. Compact (short keys — line item
 * property values have practical length limits), complete, versioned.
 * No DOM, no Shopify.
 */

export const SPEC_VERSION = 1;
export const ENGINE_VERSION = '1.0.0';

/* Practical safety budget for one line-item property value. */
export const SPEC_BYTE_BUDGET = 1800;

/*
 * Spec shape (v1):
 * {
 *   v: 1,
 *   t: "name-sign",          // schema id
 *   e: "1.0.0",              // engine version that wrote it
 *   p: { <shortKey>: value } // params, keyed by schema param short keys
 *   a: { h, layer, x, y, s, r }?  // uploaded-asset placement, content by hash reference
 * }
 * Uploaded asset *content* never lives in the spec — it is referenced by
 * hash and stored in separate `_asset_*` properties (see chunkAsset).
 */

export function buildSpec(schema, values) {
  const p = {};
  for (const param of schema.params) {
    const v = values[param.key];
    if (v === undefined || v === null || v === '') continue;
    if (param.default !== undefined && v === param.default && !param.alwaysInSpec) {
      /* Defaults are omitted for compactness but restored on load. */
      continue;
    }
    p[param.s || param.key] = v;
  }
  return { v: SPEC_VERSION, t: schema.id, e: ENGINE_VERSION, p };
}

/* Deterministic serialization: fixed top-level order, sorted param keys. */
export function serializeSpec(spec) {
  const p = {};
  for (const k of Object.keys(spec.p || {}).sort()) p[k] = spec.p[k];
  const out = { v: spec.v, t: spec.t, e: spec.e, p };
  if (spec.a) out.a = spec.a;
  return JSON.stringify(out);
}

export function deserializeSpec(json) {
  let spec;
  try {
    spec = typeof json === 'string' ? JSON.parse(json) : json;
  } catch (err) {
    throw new Error(`spec is not valid JSON: ${err.message}`);
  }
  if (!spec || typeof spec !== 'object') throw new Error('spec is not an object');
  if (spec.v === undefined) throw new Error('spec has no version');
  return migrateSpec(spec);
}

/* Version migrations. v1 is current; the ladder exists so a spec written
   today still regenerates in a year. */
export function migrateSpec(spec) {
  let s = spec;
  if (s.v > SPEC_VERSION) {
    throw new Error(`spec version ${s.v} is newer than this engine (v${SPEC_VERSION})`);
  }
  /* Future: if (s.v === 1) s = migrateV1toV2(s); */
  return s;
}

/* Restore full param values from a spec against its schema:
   short keys resolved, omitted params re-filled from defaults, every
   numeric clamped to schema min/max so an out-of-range stored value can
   never reach geometry or pricing. */
export function specToValues(spec, schema) {
  if (spec.t !== schema.id) {
    throw new Error(`spec is for "${spec.t}", schema is "${schema.id}"`);
  }
  const values = {};
  for (const param of schema.params) {
    const short = param.s || param.key;
    let v = spec.p && short in spec.p ? spec.p[short] : param.default;
    if (v !== undefined) values[param.key] = clampParamValue(param, v);
  }
  return values;
}

export function clampParamValue(param, v) {
  if (param.type === 'number') {
    let n = Number(v);
    if (!Number.isFinite(n)) n = param.default ?? param.min ?? 0;
    if (param.min !== undefined) n = Math.max(param.min, n);
    if (param.max !== undefined) n = Math.min(param.max, n);
    if (param.step) n = Math.round(n / param.step) * param.step;
    return Number(n.toFixed(4));
  }
  if (param.type === 'text') {
    let s = String(v);
    if (param.max) s = s.slice(0, param.max);
    return s;
  }
  if (param.type === 'choice') {
    const ok = (param.options || []).some((o) => (o.v ?? o) === v);
    return ok ? v : param.default;
  }
  if (param.type === 'toggle') return Boolean(v) || v === 'auto' ? v : false;
  return v;
}

export function specByteLength(spec) {
  /* UTF-8 byte length without depending on TextEncoder (Node + browser). */
  const s = serializeSpec(spec);
  let bytes = 0;
  for (let i = 0; i < s.length; i++) {
    const c = s.codePointAt(i);
    bytes += c < 0x80 ? 1 : c < 0x800 ? 2 : c < 0x10000 ? 3 : (i++, 4);
  }
  return bytes;
}

/* djb2 content hash for asset references — short, stable, sufficient for
   correlating a spec with its `_asset_*` properties. */
export function assetHash(content) {
  let h = 5381;
  for (let i = 0; i < content.length; i++) {
    h = ((h << 5) + h + content.charCodeAt(i)) >>> 0;
  }
  return h.toString(36);
}

/*
 * Uploaded artwork is stored OUTSIDE the spec: chunked into additional
 * hidden line-item properties so no single value exceeds the budget.
 * Returns { ref, properties } — `ref` goes into spec.a.h, `properties`
 * are merged into the cart item's hidden properties.
 */
export function chunkAsset(content, { chunkSize = 1500 } = {}) {
  const h = assetHash(content);
  const properties = {};
  const chunks = Math.ceil(content.length / chunkSize);
  for (let i = 0; i < chunks; i++) {
    properties[`_asset_${h}_${i}`] = content.slice(i * chunkSize, (i + 1) * chunkSize);
  }
  properties[`_asset_${h}_n`] = String(chunks);
  return { ref: h, properties };
}

/* Reassemble from a properties object (regenerate.html uses this). */
export function reassembleAsset(properties, ref) {
  const n = Number(properties[`_asset_${ref}_n`]);
  if (!Number.isFinite(n) || n <= 0) return null;
  let out = '';
  for (let i = 0; i < n; i++) {
    const part = properties[`_asset_${ref}_${i}`];
    if (part === undefined) return null;
    out += part;
  }
  return out;
}
